### ISSUE TITLE
`knockoff` method throws StackOverflowError

### ISSUE THREAD

**Issue by ardok** [tristanjuricek/knockoff#35]
I'm using Scala 2.10.2, hence using 0.8.1 version.

Calling `knockoff` method keeps throwing me this:

java.lang.StackOverflowError: null
    at java.util.regex.Pattern.group0(Pattern.java:2513) ~[na:1.6.0_26]
    at java.util.regex.Pattern.sequence(Pattern.java:1806) ~[na:1.6.0_26]
    at java.util.regex.Pattern.expr(Pattern.java:1752) ~[na:1.6.0_26]
    at java.util.regex.Pattern.compile(Pattern.java:1460) ~[na:1.6.0_26]
    at java.util.regex.Pattern.<init>(Pattern.java:1133) ~[na:1.6.0_26]
    at java.util.regex.Pattern.compile(Pattern.java:823) ~[na:1.6.0_26]
    at scala.util.matching.Regex.<init>(Regex.scala:153) ~[scala-library-2.10.2.jar:na]
    at scala.collection.immutable.StringLike$class.r(StringLike.scala:224) ~[scala-library-2.10.2.jar:na]
    at scala.collection.immutable.StringOps.r(StringOps.scala:31) ~[scala-library-2.10.2.jar:na]
    at scala.collection.immutable.StringLike$class.r(StringLike.scala:213) ~[scala-library-2.10.2.jar:na]
    at scala.collection.immutable.StringOps.r(StringOps.scala:31) ~[scala-library-2.10.2.jar:na]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:261) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]
    at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270) ~[knockoff_2.10-0.8.1.jar:0.8.1]

Any idea?

Oh and just to add more info, using the version for Scala 2.9 works just fine.

UPDATE 08/29/13 10:06 : will try increasing stack size and cross my fingers

**Comment by tristanjuricek** [comment]
I haven't done anything in Scala in a while, so I'm not sure. I'll check it out when I have some free time.

The expression that's failing is 

```
"(?i)<[ ]*" + tagName + "[ ]*[^>]*>"
```

This is a basic search for HTML tags. I may have to sanitize that tag name, is there any kind of interesting HTML in the document you're trying to parse?

**Comment by devmage** [comment]
I'm one of @ardok 's colleagues. We ran JProfiler against this section of code. Just to show you: http://i.imgur.com/bv63l36.png

That CPU time tree is from 3-4 minutes of execution time, most of which were spent compiling a markdown file we have. The tree extends quite far beyond what is shown here.

**Comment by tristanjuricek** [comment]
I just updated the 2.10 build to 2.10.2, it doesn't really seem that it's build related at all, which makes sense.

How are HTML tags being used? Is there any stretch of code that appears like an HTML tag? Like `<foo`?

**Comment by ardok** [comment]
I don't think there is any.
There was something like `[link](blah blah` without parenthese closure and it gave us `None.get` error.
After fixing that, we faced that StackOverflowError. It's just that recursive `findEnd` method.
What I did to "fix" it is reverting your HTMLBlock changes and making it Scala 2.10 ready. 
Markdown loads much faster than using HTMLBlock.

**Comment by ardok** [comment]
FYI, this is what we're currently using: https://github.com/ardok/knockoff/tree/non-recursive

I reverted your master branch to this commit: https://github.com/tristanjuricek/knockoff/commit/74bfe4bc3b6cdddcd417f38e1514b5574c11c44a  (before you add `emptySpace`) and updated it to use Scala 2.10

**Comment by tristanjuricek** [comment]
Thanks!

What I really use is a  reproduction case, I'm still not able to actually
generate the problem this change solves.

-Tristan

**Comment by ardok** [comment]
Give this a shot with your `master` branch: https://github.com/stackmob/stackmob-docs/blob/master/sdks/ios/guides/developer.md

**Comment by razie** [comment]
i just had the same issue on a fresh install of a scala play app on a ubuntu 32 bit VM. the exact same install on a 64 bit VM works fine - can't explain it, but it must be due to some environment issues.

the content it tries to parse has a few html tags, yes... without the tags it works fine every time.

i'm using 0.8.1

**Comment by ardok** [comment]
The one that works fine for me is this from this commit (dated July 22, 2012): https://github.com/tristanjuricek/knockoff/commit/74bfe4bc3b6cdddcd417f38e1514b5574c11c44a

I forked from that commit and update it to use scala 2.10.2.
This is what I'm using for now: https://github.com/ardok/knockoff/tree/non-recursive

If you're gonna use my forked repo, just remember to change the version in `build.sbt` since it has my name on the version build.
